DATASET=$1
SEARCH_TYPE=$2
SEARCH_SPACE=$3
LINE_NUM=$4
NUM_MODELS_IN_FILE=$5

bash load_one_model.sh ~/datasets/$DATASET/ ~/datasets/$DATASET'_vecs.txt' ../output/$DATASET'_'$SEARCH_TYPE'_'$SEARCH_SPACE'_'$LINE_NUM'_'$NUM_MODELS_IN_FILE $SEARCH_TYPE $SEARCH_SPACE 3 $LINE_NUM $NUM_MODELS_IN_FILE
